const asyncHandler = require('../utils/asyncHandler');
const ApiResponse = require('../utils/ApiResponse');
const Task = require('../models/Task');
const aiService = require('../services/aiService');
const { ERROR_CODES } = require('../utils/constants');

const getTasks = asyncHandler(async (req, res) => {
  const { done, priority, source } = req.query;
  const query = { userId: req.user._id };
  
  if (done !== undefined) query.done = done === 'true';
  if (priority) query.priority = priority;
  if (source) query.source = source;

  const tasks = await Task.find(query).sort({ createdAt: -1 });
  res.json(ApiResponse.success(tasks, 'Tasks fetched successfully'));
});

const getTask = asyncHandler(async (req, res) => {
  const task = await Task.findOne({ _id: req.params.id, userId: req.user._id });
  if (!task) {
    return res.status(404).json(ApiResponse.error(ERROR_CODES.NOT_FOUND, 'Task not found'));
  }
  res.json(ApiResponse.success(task, 'Task fetched'));
});

const createTask = asyncHandler(async (req, res) => {
  const { title, priority, deadline, source, time, externalId } = req.body;
  const task = await Task.create({
    userId: req.user._id,
    title,
    priority: priority || 'Normal',
    deadline,
    source: source || 'Manual',
    time,
    externalId
  });
  res.status(201).json(ApiResponse.success(task, 'Task created'));
});

const updateTask = asyncHandler(async (req, res) => {
  const task = await Task.findOneAndUpdate(
    { _id: req.params.id, userId: req.user._id },
    req.body,
    { new: true, runValidators: true }
  );
  
  if (!task) {
    return res.status(404).json(ApiResponse.error(ERROR_CODES.NOT_FOUND, 'Task not found'));
  }
  
  res.json(ApiResponse.success(task, 'Task updated'));
});

const deleteTask = asyncHandler(async (req, res) => {
  const task = await Task.findOneAndDelete({ _id: req.params.id, userId: req.user._id });
  if (!task) {
    return res.status(404).json(ApiResponse.error(ERROR_CODES.NOT_FOUND, 'Task not found'));
  }
  res.json(ApiResponse.success(null, 'Task deleted'));
});

const generateTasks = asyncHandler(async (req, res) => {
  const tasks = await aiService.generateDayTasks(req.user._id);
  res.json(ApiResponse.success(tasks, 'Tasks generated by AI'));
});

module.exports = { getTasks, getTask, createTask, updateTask, deleteTask, generateTasks };
